todo_app/urls.py
from django.urls import path

from todo_app.views import \
    TaskListView, \
    TagListView, \
    TaskCreateView, \
    toggle_done, \
    TaskUpdateView, \
    TaskDeleteView, \
    TagsCreateView, \
    TagsDeleteView, \
    TagsUpdateView

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tags/", TagListView.as_view(), name="tags-list"),
    path("task-create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/toggle-done/", toggle_done, name="toggle-done"),
    path("<int:pk>/task-update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/task-delete/", TaskDeleteView.as_view(), name="task-delete"),
    path(
        "tags/tags-create/",
        TagsCreateView.as_view(),
        name="tag-create",
    ),
    path(
        "tags/<int:pk>/tags-update/",
        TagsUpdateView.as_view(),
        name="tag-update",
    ),
    path(
        "tags/<int:pk>/tags-delete/",
        TagsDeleteView.as_view(),
        name="tag-delete",
    ),
]

app_name = "todo_app"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # path('admin/', admin.site.urls),
    path("", include("todo_app.urls", namespace="todo_app")),
    # path("", hello_world)

]

todo_app/models.py
from django.db import models


class Tags(models.Model):
    name = models.CharField(max_length=69)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField()
    tags = models.ManyToManyField(Tags)

    class Meta:
        ordering = ["is_done", "created_at"]

todo_app/forms.py
from django import forms

from todo_app.models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"

todo_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from todo_app.forms import TaskForm
from todo_app.models import Task, Tags


class TaskListView(generic.ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "todo_app/task_list.html"


class TagListView(generic.ListView):
    model = Tags


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo_app:task-list")


def toggle_done(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.is_done = not task.is_done
    task.save()

    return HttpResponseRedirect(reverse_lazy("todo_app:task-list"))


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo_app:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo_app:task-list")


class TagsCreateView(generic.CreateView):
    model = Tags
    fields = "__all__"
    queryset = Task.objects.all().prefetch_related("tags")
    success_url = reverse_lazy("todo_app:tags-list")


class TagsUpdateView(generic.UpdateView):
    model = Tags
    fields = "__all__"
    success_url = reverse_lazy("todo_app:tags-list")


class TagsDeleteView(generic.DeleteView):
    model = Tags
    fields = "__all__"
    success_url = reverse_lazy("todo_app:tags-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Todo list</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% load static %}
{#  {% if user.is_authenticated %}#}
{#    <li class="list-group-item">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>#}
{#    <li class="list-group-item"><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>#}
{#  {% else %}#}
{#    <li class="list-group-item"><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>#}
{#  {% endif %}#}

  <br>

  <li class="list-group-item"><a href="{% url 'todo_app:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo_app:tags-list' %}">Tags</a></li>

</ul>

templates/todo_app/tags_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <input type="submit" value="No" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo_app/tags_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo_app/tags_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Manufacturer List
    <a href="{% url 'todo_app:tag-create' %}" class="btn btn-primary link-to-page">
      Add tags
    </a>
  </h1>
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-secondary" type="submit" value="🔎">
  </form>

  {% if tags_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tags_list %}
        <tr>
          <td>
              {{ tag.id }}
          </td>
          <td>
              {{ tag.name }}
          </td>
          <td>
              <a href="{% url 'todo_app:tag-update' pk=tag.id %}" class="btn btn-outline-secondary btn-sm">
                Update
              </a>
            </td>
            <td>
              <a href="{% url 'todo_app:tag-delete' pk=tag.id %}" class="btn btn-outline-secondary btn-sm">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no tags in the todo list.</p>
  {% endif %}
{% endblock %}

templates/todo_app/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <input type="submit" value="No" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo_app/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo_app/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    TODO list
    <a href="{% url 'todo_app:task-create' %}" class="btn btn-primary link-to-page">
      Add task
    </a>
  </h1>
  {% for task in task_list %}
    <p>
      {% if task.is_done %}
        <h4>{{ task.content }}</h4>Done
        <a href="{% url 'todo_app:toggle-done' pk=task.id %}" class="btn btn-success link-to-page">
          Undo
        </a>
      {% else %}
        <h4>{{ task.content }}</h4>Not done
        <a href="{% url 'todo_app:toggle-done' pk=task.id %}" class="btn btn-danger link-to-page">
          Complete
        </a>
      {% endif %}
    <p><strong>Created: </strong> {{ task.created_at}}
      {% if task.deadline %}<strong>Deadline: </strong>{{ task.deadline }} {% endif %}
    </p>
    {% for tag in task.tags.all %}
      <p><strong>Tags: </strong>{{ tag.name }}
    {% endfor %}
      <a href="{% url 'todo_app:task-update' pk=task.id %}" >
        Update
      </a>
      <a href="{% url 'todo_app:task-delete' pk=task.id %}" >
        Delete
      </a>
  </p>
  {% empty %}
    <p>No tasks!</p>
  {% endfor %}
{% endblock %}